services:
  - type: web
    name: codealpha-ecommerce-store
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir ecommerce ecommerce.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: 2
